spring:
  application:
    name: picpay
  jpa:
    show-sql: true
    hibernate:
      dll-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/picpaydb
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:123}
    driver-class-name: com.mysql.cj.jdbc.Driver
