spring:
  application:
    name: picpay
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/picpaydb
    username: ${MYSQL_USER:admin}
    password: ${MYSQL_PASSWORD:123}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    openfeign:
      client:
        config:
          authorization-client:
            url: https://run.mocky.io/v3/eb7d80cc-e966-434f-bf44-08ea515fc4e7
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: full
          notification-client:
            url: https://run.mocky.io/v3/0f3987f5-06b1-4670-ae10-0f88a0d6caf7
            connect-timeout: 5000
            read-timeout: 5000
            logger-level: full

